### ISSUE TITLE
Deployment 2020-2.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-SST/profile_collection#12]
## Previsit 
- [x] Make sure that the current latest environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Check if beamline specific packages pushed to the BL machines
- [x] (Optional) Enable CI

## Housekeeping 
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the profile as-found as 2019C3.x
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)

## Test deployment 
- [x] In `~/.bashrc` add the following and remember to `source ~/.bashrc` afterward.
  ```
  BLUESKY_LOG_FILE=/var/log/bluesky.log
  BLUESKY_IPYTHON_LOG_FILE=/var/log/bluesky_ipython.log
  ```
  and (if needed) create those directories, making them world-read/write-able.
- [x] Append to `00-startup.py`  https://gist.github.com/jklynch/a4366b8900ec0c03883403455ae711b2
- [x] Run profile against new environment
  - `BS_ENV=collection-2020-2.0rc7 bsui`
- [ ] Update the profile as needed to run:
  - [x] Replace `.value` -> `.get()` if it's in a `Device`, or with `yield from bps.read()` if in a plan
  - [x] `history.sqlite` issue - see https://blueskyproject.io/bluesky/metadata.html#persistence-between-sessions
  - [ ] potential issue with images in databroker V2
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline
- [x] Tag the updated profile as `2020C2.0`
- [x] Update BSUI via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)
