### ISSUE TITLE
Deployment 2021-1.0 checklist

### ISSUE THREAD

**Issue by jklynch** [NSLS-II-SST/profile_collection#15]
## Previsit 
- [x] Make sure that the current latest environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Branch https://github.com/NSLS-II/playbooks for the purpose of updating the SST `current_env_tag` in the `production` file

## Housekeeping 
- [x] Update conda
  ```
  $ su - <your-controls-account>
  $ sudo su -
  # conda activate base  # should be activated by default, but just in case.
  # conda install conda -c https://repo.anaconda.com/pkgs/main/
  ```
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the profile_collection repository as-found as 2020C2.1
   ```bash
   $ git tag -a 2020C2.1
   ```
   Enter a message such as `Before 2021C1.0 deployment.`
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's workstation inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)
- [x] In `~/.bashrc`, if necessary, update the logging environment variables to use directory `/var/log/bluesky/...` and add `umask 0002`.
  ```
  umask u=rwx,g=rwx,o=rx  # 0002
  export BLUESKY_LOG_FILE=/var/log/bluesky/bluesky.log
  export BLUESKY_IPYTHON_LOG_FILE=/var/log/bluesky/bluesky_ipython.log
  ```
  and (if needed) create that directory with the following permissions and ownership:
  ```
  sudo mkdir /var/log/bluesky
  sudo chown -Rv xf07id1:xf07id1 /var/log/bluesky
  sudo chmod -Rv g+rws /var/log/bluesky
  ```
  Remember to `source ~/.bashrc`.
- [x] Remove explicit setting of ophyd logging level from the first startup script
- [x] Double-check that if there is an open PR removing handlers, it is merged (and tested).
- [x] Update vendored copy of `PersistentDict` to bug-fixed version (see the updated gist snippet: https://gist.github.com/jklynch/a4366b8900ec0c03883403455ae711b2).
- [x] Make sure all repos have the BSD-3-Clause licenses (see https://github.com/NSLS-II-SRX/profile_collection/pull/16 as an example)

## Test deployment 
- [x] Run profile against new environment
```bash
 $ BS_ENV=collection-2021-1.0 bsu
```
It may be necessary to disable `jedi` in `ipython`. Add this to the `ipython` command line arguments in`bsui`:
   ```bash
   --IPCompleter.use_jedi=False
   ```
- [x] Update the profile as needed to run
- [x] Test databroker v2
  ```
  from databroker import catalog
  cat = catalog['beamline_name']
  cat[-1].primary.read()
  ```
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline

## Finish
- [x] Tag the updated profile as `2021C1.0`
   ```bash
   $ git tag -a 2021C1.0
   ```
   Enter a message such as `After 2021C1.0 deployment.`

- [x] Open and merge a PR against https://github.com/NSLS-II/playbooks setting `current_env_tag="2021-1.0"` for the SST beamline
- [x] Update BSUI via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by MikeHart85** [comment]
Deployment completed on 8 Jan 2021. Closing issue.
